# Generated by Django 4.2.2 on 2024-02-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
