# Generated by Django 4.2.2 on 2024-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='addemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
