# Generated by Django 4.2.2 on 2024-02-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_addemployee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addemployee',
        ),
    ]
