# Generated by Django 4.2.2 on 2024-02-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
