# Generated by Django 4.2.2 on 2024-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
