# Generated by Django 4.2.2 on 2024-02-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_validlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
