# Generated by Django 4.2.2 on 2024-02-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
