# Generated by Django 4.2.2 on 2024-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.CharField(default='50', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='john doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='00000000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
