# Generated by Django 5.0.1 on 2024-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place_of_counselling', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('finacial_status', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=15)),
                ('religion', models.CharField(default='null', max_length=20, null=True)),
                ('fathers_occupation', models.CharField(default='null', max_length=25, null=True)),
                ('mothers_occupation', models.CharField(default='null', max_length=25, null=True)),
                ('fathers_education', models.CharField(default='null', max_length=25, null=True)),
                ('mothers_education', models.CharField(default='null', max_length=25, null=True)),
                ('problem', models.CharField(max_length=200)),
                ('history_of_problem', models.CharField(default='null', max_length=500, null=True)),
                ('intervention', models.CharField(default='null', max_length=100, null=True)),
                ('challenges_by_counsellor', models.CharField(default='null', max_length=200, null=True)),
                ('number_of_followup_sections', models.CharField(max_length=10)),
                ('referral_service', models.CharField(default='null', max_length=100, null=True)),
                ('outcome', models.CharField(default='null', max_length=250, null=True)),
                ('remarks', models.CharField(default='null', max_length=200, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
