# Generated by Django 5.0.1 on 2024-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consellor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='email',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
