# Generated by Django 5.0.1 on 2024-02-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consellor', '0002_counsellor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='school',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
    ]
