# Generated by Django 4.2.2 on 2024-03-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consellor', '0003_alter_counsellor_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
