# Generated by Django 4.2.2 on 2024-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consellor', '0004_alter_counsellor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='name',
            field=models.CharField(default='xyz', max_length=20),
        ),
    ]
