# Generated by Django 4.2.2 on 2024-03-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consellor', '0005_alter_counsellor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='nameofcounsellor',
            field=models.CharField(default='xyz', max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
