# Generated by Django 4.2.2 on 2024-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consellor', '0008_alter_counsellor_challenges_by_counsellor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='uniqueid',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
