# Generated by Django 4.2.2 on 2024-03-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0002_ptsessions_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsessions',
            name='uniqueid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
