# Generated by Django 4.2.2 on 2024-03-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptsessions', '0003_alter_ptsessions_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsessions',
            name='uniqueid',
            field=models.CharField(max_length=100),
        ),
    ]
